/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.esql.qa.simulator;

import net.jqwik.api.lifecycle.AroundPropertyHook;
import net.jqwik.api.lifecycle.PropertyExecutionResult;
import net.jqwik.api.lifecycle.PropertyExecutor;
import net.jqwik.api.lifecycle.PropertyLifecycleContext;

/**
 * jqwik lifecycle hook that overrides property seed from system properties.
 * <p>
 * Usage: pass {@code -Dsimulator.seed=12345} to replay a specific seed.
 * <p>
 * Note: shrinking mode is configured via {@code junit-platform.properties} (generated by Gradle
 * from {@code -Dsimulator.shrinking=FULL}), because jqwik reads shrinking mode before
 * lifecycle hooks run.
 */
public class SimulatorSeedHook implements AroundPropertyHook {
    @Override
    public PropertyExecutionResult aroundProperty(PropertyLifecycleContext context, PropertyExecutor property) throws Exception {
        String seed = System.getProperty("simulator.seed");
        if (seed != null) {
            context.attributes().setSeed(seed);
        }
        return property.execute();
    }
}
